// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurentMS_Final_Project.Data;

#nullable disable

namespace RestaurentMS_Final_Project.Migrations
{
    [DbContext(typeof(RestaurentMSDbContext))]
    [Migration("20221217131437_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestaurentMS_Final_Project.Models.MenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MenuCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("menuCategories");
                });

            modelBuilder.Entity("RestaurentMS_Final_Project.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MenuItemPrice")
                        .HasColumnType("float");

                    b.Property<int>("menuCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("menuCategoryId");

                    b.ToTable("menuItems");
                });

            modelBuilder.Entity("RestaurentMS_Final_Project.Models.MenuItem", b =>
                {
                    b.HasOne("RestaurentMS_Final_Project.Models.MenuCategory", "menuCategory")
                        .WithMany()
                        .HasForeignKey("menuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menuCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
